---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes

dotfiles_repo: git@github.com:DaneW/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore_global
  - .inputrc
  - .macos

homebrew_installed_packages:
  - ant@1.9
  - aspell
  - automake
  - bash-completion
  - ccm
  - curl
  - exa
  - git
  - grep
  - jq
  - kubernetes-cli
  - libtool
  - mas
  - micro
  - nmap
  - opencv
  - openssl@1.1
  - packer
  - pv
  - pyenv-virtualenvwrapper
  - rbenv
  - terraform
  - tmux
  - watchman
  - wget
  - yarn

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []
  # - docker
  # - dropbox
  # - firefox
  # - google-chrome
  # - slack
  # - vagrant
  # - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
